version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: my-redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # This line enables data persistence
    restart: always # Ensures Redis restarts if it stops or Docker restarts
    # Optional: Add a password for security (highly recommended for production)
    # command: redis-server --requirepass your_strong_password
    # environment:
    #   - REDIS_PASSWORD=your_strong_password # For Redis Stack image

volumes:
  redis_data: # Defines a named volume for persistence
